env: # Environt variable to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone repo
task:
    name: wow 
    timeout_in: 240m
    container:
      image: mrkhan007/aosp:latest
      cpu: 8
      memory: 32G
   # download_ccache_script:
     # - bash download_ccache
    sync_script:
      - bash sync
    build_script:
      - bash build
    upload_ccache_script:
      - bash upload_ccache


#start Building 
