#!/bin/bash

url=https://transfer.sh/1u6vyWx/ccache-example.tar.gz

cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50
echo "dl done"
time tar xf ccache-example.tar.gz 
echo "unzip done"
find ccache-example.tar.gz -delete
