#!/bin/bash

url=https://ghostmirror.hitesh920.workers.dev/kang32.tar.gz

cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50
echo "dl done"
time tar xf kang32.tar.gz
echo "unzip done"
find kang32.tar.gz -delete
