#!/bin/bash
sudo apt install wget

mkdir -p /tmp/rom
cd /tmp/rom

repo init -u https://github.com/PixelExperience/manifest -b eleven

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8


##delete these lines, and replace with your own lines of device sauce
git clone https://github.com/noobyysauraj/proprietary_vendor_realme_RMX2151.git vendor/realme/RMX2151
git clone https://github.com/noobyysauraj/device_realme_RMX2151.git device/realme/RMX2151

cd /tmp/rom
