#!/bin/bash
sudo apt install wget
MANIFEST=https://github.com/PixelExperience/manifest
BRANCH=TEN

mkdir -p /tmp/rom
cd /tmp/rom

git clone https://github.com/Akash23q2/vendor_lenovo_TBX304
git clone https://github.com/Akash23q2/device_lenovo_TBX304

cd /tmp/rom
