#!/bin/bash
sudo apt install wget

mkdir -p /tmp/rom
cd /tmp/rom

repo init -u https://github.com/ArrowOS/android_manifest -b arrow-11.0

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

##delete these lines, and replace with your own lines of device sauce
git clone https://github.com/Akash23q2/device_asus_X00P
git clone https://github.com/danascape-projects/vendor_asus_X00P-old -b eleven 
cd /tmp/rom
